### ISSUE TITLE
So i was looking around in the bot when i saw a error (I have NOT modified anything)

### ISSUE THREAD

**Issue by Coocktail** [FirezzzZ/1SHOT#11]
bot.channels.cache.get(message.channel.id).send(x.join(" "));
                                           ^

TypeError: Cannot read property 'channel' of undefined

Error is in console.js file

**Comment by FirezzzZ** [comment]
add message parameter in module.exports
also show the whole code in console.js file

**Comment by Coocktail** [comment]
module.exports = (bot, message) => {
    let prompt = process.openStdin()
    prompt.addListener("data", res => {
        let x = res.toString().trim().split(/ +/g)
            bot.channels.cache.get(message.channel.id).send(x.join(" "));
        });
    };

**Comment by FirezzzZ** [comment]
idk should work
