### ISSUE TITLE
Not working command .instasearch

### ISSUE THREAD

**Issue by leonvva** [FirezzzZ/1SHOT#4]
I dont now why not working command .instasearch. Bot just says "I couldn't find that account".

**Comment by FirezzzZ** [comment]
I can reproduce the bug but idk why it happens, some problem with the api, i guess. i will remove this command and later in the future i will make a code for this command again

**Comment by Coocktail** [comment]
I found a fix for this

**Comment by FirezzzZ** [comment]
please tell

**Comment by Coocktail** [comment]
here

**Comment by Coocktail** [comment]
(the code is entirely different so umm yea)

**Comment by Coocktail** [comment]
just wait i will send code through pastebin

**Comment by Coocktail** [comment]
https://pastebin.com/3196TzxQ (u need common-tags)

**Comment by Coocktail** [comment]
and node-fetch

**Comment by Coocktail** [comment]
@FirezzzZ i know i didnt change a lot but still it wrks(maybe)

**Comment by Coocktail** [comment]
and i am still getting the same error in my issue

**Comment by FirezzzZ** [comment]
> https://pastebin.com/3196TzxQ (u need common-tags)

fix
