### ISSUE TITLE
Self-Hosting reated

### ISSUE THREAD

**Issue by Coocktail** [FirezzzZ/1SHOT#5]
So i have my bot and i would like to add some commands and make separate folders for them (ex Like giveaway and stuff) but when i do it i get errors. So i guess i will have to change some files so how can i make it work.

**Comment by FirezzzZ** [comment]
create the folder(inside commands folder only), copy the name and paste it inside the array in the `command.js` file inside handler folder. done

**Comment by Coocktail** [comment]
yea i did that

**Comment by Coocktail** [comment]
but now i have moved some of the commands like setprefix and other configuration commands to another folder but i still see the moved commands in the moderation category, any fixes
(and if u want my github repo then tell me)

**Comment by FirezzzZ** [comment]
change the category name inside the file's config part, ```
module.exports = { 
      config: {
         ...
      }
}```

**Comment by Coocktail** [comment]
if (pull.config.aliases) pull.config.aliases.forEach(a => bot.aliases.set(a, pull.config.name));
2:22:08 PM:                                                          ^
2:22:08 PM: TypeError: pull.config.aliases.forEach is not a function
it used to work till i made a few more commands

**Comment by Coocktail** [comment]
new error

**Comment by Coocktail** [comment]
what can possibly be a cause for it

**Comment by FirezzzZ** [comment]
check the aliases: for every config in each file, it should have these `aliases: ['']` or else it would error

**Comment by Coocktail** [comment]
oki
doki

**Comment by Coocktail** [comment]
ty

**Comment by Coocktail** [comment]
still same error

**Comment by FirezzzZ** [comment]
check again

**Comment by Coocktail** [comment]
https://pastebin.com/H0XhbkDn
https://pastebin.com/pnCLrvMV
https://pastebin.com/9BXZ3XdM
All the files that possible cause the error so what is the error in them??

**Comment by FirezzzZ** [comment]
![Screenshot_20200727-110141](https://user-images.githubusercontent.com/55920870/88506870-9b25b480-cff8-11ea-9466-7f4ab1980716.jpg)
["grr"]

**Comment by Coocktail** [comment]
what do i need to do there??

**Comment by Coocktail** [comment]
change it to something else??

**Comment by Coocktail** [comment]
@FirezzzZ

**Comment by Coocktail** [comment]
lol sry its ['grr']

**Comment by Coocktail** [comment]
not "[grr]"

**Comment by FirezzzZ** [comment]
that is what i wrote above..

**Comment by Coocktail** [comment]
yes sry

**Comment by Coocktail** [comment]
Hey umm how to make a command not work in a non-nsfw channel (Cuz of the love cmd
)

**Comment by FirezzzZ** [comment]
```js
let channel = message.guild.channels.cache.get('id') //u can use mentions.first() or anything else which returns TextChannel Object
if (!channel.nsfw) return message.channel.send('Not A NSFW Channel!'); //checks if its a nsfw channel or not, nsfw returns a boolean
```
