### ISSUE TITLE
Hey FirezzzZ, Can you please add reaction roles?

### ISSUE THREAD

**Issue by Coocktail** [FirezzzZ/1SHOT#8]
Please consider adding reaction roles to 1shot If you need help go here: https://github.com/stuyy/Discord.JS-V12-Tutorials/tree/master/src/commands/rolereactions

**Comment by rubiksking124** [comment]
reaction roles are not hard to code

**Comment by FirezzzZ** [comment]
Okay ill try to make it

**Comment by Coocktail** [comment]
Thanks

**Comment by rubiksking124** [comment]
i could help you make it if you want i know how to do it in mongo and im pretty sure i know how with quick.db

**Comment by Coocktail** [comment]
Oh

**Comment by Coocktail** [comment]
With quick.db?

**Comment by Coocktail** [comment]
And How

**Comment by rubiksking124** [comment]
with quick.db it would be a bit more weird then with mongo but it can be done

**Comment by Coocktail** [comment]
Oh
(So umm can i have the code)

**Comment by rubiksking124** [comment]
https://github.com/rubiksking124/Reaction-roles-.git sorry it took so long I was creating it and uploading it to github

**Comment by Coocktail** [comment]
OMG TY
I really wanted reaction roles for my server tyyyyyyyyyyyyyyy
